spring:
  rabbitmq:
    host: 192.168.88.132 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /hmall # 虚拟主机(用户只能使用自己创建的虚拟主机)
    username: hmall # 用户名
    password: 1234 # 密码

logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS



