logging:
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS
    level:
      com.itheima: debug
spring:
  rabbitmq:
    host: 192.168.88.132 # 你的虚拟机IP
    port: 5672 # 端口
    virtual-host: /hmall # 虚拟主机(用户只能使用自己创建的虚拟主机)
    username: hmall # 用户名
    password: 1234 # 密码
    connection-timeout: 1s
    template:
      retry:
        enabled: true
        multiplier: 2
    publisher-confirm-type: correlated # 开启publisher confirm机制，并设置confirm类型
    publisher-returns: true # 开启publisher return机制 (这个一般不开启，为了看到结果测试才开启)
